# Generated by Django 5.0.1 on 2024-05-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0002_trainer_address_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='regDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('tot', models.IntegerField(null=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('desc', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(default='Any Age', max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('exptime', models.CharField(max_length=50, null=True)),
                ('available', models.CharField(default='Not Available', max_length=50)),
                ('status', models.CharField(default='Not Approved', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('company', models.CharField(max_length=50, null=True)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.shops')),
            ],
        ),
        migrations.CreateModel(
            name='ChildBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('tot', models.IntegerField(null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.booking')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.products')),
            ],
        ),
    ]
