# Generated by Django 5.0.1 on 2024-05-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0003_alter_login_regdate_booking_products_childbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.user')),
            ],
        ),
    ]
