# Generated by Django 5.0.1 on 2024-05-27 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0006_articles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.trainer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuel.user')),
            ],
        ),
    ]
