# Generated by Django 5.0.1 on 2024-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0007_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
